### ISSUE TITLE
File disappeared

### ISSUE THREAD

**Issue by cajstudy** [bernard0047/style-splat#1]
Excuse me, is the source code fully open source? There are a lot of problems in the process of reproduction, and some files will be missing

**Comment by bjxdw** [comment]
Yes, I encountered the same issue. A lot of problems...

**Comment by bernard0047** [comment]
Thanks for your interest and for pointing this out. There was a missing file and a few minor bugs, which have now been fixed. I’ve checked the repository, and it runs as expected. Please pull the latest changes and try again. 

Best,
Avik
