### ISSUE TITLE
Question about 25% of the training images

### ISSUE THREAD

**Issue by zhanglk9** [bernard0047/style-splat#2]
“The style transfer optimization is then performed using 25% of the training
images” in paper. Where can I find this part in the code?? Does the quantity have a big impact on the effect?

**Comment by bernard0047** [comment]
It's just to speed things up. Since loading bigger datasets could take longer, we found and noted that using 25% of the training images produces similar results too. You can use list comprehension to skip loading some images

**Comment by dhsoon02** [comment]
Hi, I have a question regarding a dataset.
I would like to run the code and check the results myself, but I was wondering how I can download or locate the dataset.

Where did you guys get the dataset, I'd love to know how you did it.
