### ISSUE TITLE
How to show the final effect

### ISSUE THREAD

**Issue by cajstudy** [bernard0047/style-splat#3]
Is the three-dimensional display effect of this project also displayed through sibr_viewer? Is there any other method? I am very confused as to whether the final output result file structure is correct. Can you give me an answer? Thank you so much

**Comment by bernard0047** [comment]
Our final ply output resembles the original 3DGS file structure, so SIBR_Viewer should work. In addition to that, here are couple of online tools where you can directly upload the resulting ply file and view the 3D scene: 

https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php
https://antimatter15.com/splat/
